config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]



  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord

    validates :name, presence: true
    #Tagsテーブルから中間テーブルに対する関連付け
    has_many :tweet_tag_relations, dependent: :destroy
    #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
    has_many :tweets, through: :tweet_tag_relations, dependent: :destroy

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :comments, dependent: :destroy
      #tweetsテーブルから中間テーブルに対する関連付け
    has_many :tweet_tag_relations, dependent: :destroy
      #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  has_many :tweets, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      tweet = Tweet.find(params[:tweet_id])
      comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
before_action :authenticate_user!, only: [:new, :create]


  def index
        @tweets = Tweet.all
        if params[:tag_ids]
          @tweets = []
          params[:tag_ids].each do |key, value|
            if value == "1"
              tag_tweets = Tag.find_by(name: key).tweets
              @tweets = @tweets.empty? ? tag_tweets : @tweets & tag_tweets
            end
          end
        end
      
      
        if params[:tag]
          Tag.create(name: params[:tag])
        end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)

    tweet.user_id = current_user.id 
    
    
    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end



  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:title, :date, :place, :model, :company, :about, :image, :image2, :video, :youtube_url, :people, tag_ids: [])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def find_youtube_url(youtube_url)
      if youtube_url[0..16] == "https://youtu.be/"
        return youtube_url[17..27]
        # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
      else
        return youtube_url[32..42]
        # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
      end
    end
  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>安全な空の旅のために</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a338762cbd.js"  crossorigin="anonymous"></script> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,user-scalable=no,maximum-scale=1" />
    <!--   PC用のスタイルシート(default.css)   -->
    <link rel="stylesheet" media="all" type="text/css" href="default.css" />
    <!--   タブレット用のスタイルシート(tablet.css)   -->
    <link rel="stylesheet" media="all" type="text/css" href="tablet.css" />
    <!--   スマートフォン用のスタイルシート(smartphone.css)   -->
    <link rel="stylesheet" media="all" type="text/css" href="smartphone.css" />
  </head>

<body>
  <div class="header2 header3">
    <header>
      <div class="header-r">
        <%= link_to "安全な空の旅のために", tweets_path %>
      </div>
      <div class="header-list">
        <ul>
          <% if user_signed_in? %>
          <li><%= link_to "マイページへ", user_path(current_user.id) %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </header>
 </div>
 <main>
  <%= yield %>
 </main>
</body>

</html>
 

app/views/tweets/edit.html.erb

<%= form_for @tweet do |f| %>
    <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_field :title, :size => 30 %>
  </div>


    <div class="field">
    <%= f.label :場所 %>
    <%= f.text_field :place, :size => 30 %>
    </div>


    <div class="field">
    <%= f.label :機種 %>
    <%= f.text_field :model, :size => 30 %>
    </div>


    <div class="field">
    <%= f.label :航空会社 %>
    <%= f.text_field :company, :size => 30 %>
    </div>


    <div class="field">
    <%= f.label :事故年月日 %>
    <%= f.date_field :date, :size => 30 %>
    </div>


  <div class="field">
    <%= f.label :乗客・乗員  %>
    <%= f.number_field :people, :size => 10 %>
  </div>


  <div class="field">
    <%= f.label :説明  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <div class="field">
  <%= f.label :image %>
  <%= f.file_field :images, multiple: true %>
  </div>

  <div class="field">
  <%= f.label :image2 %>
  <%= f.file_field :image2 %>
  </div>

  <%= f.label :video %>
  <%= f.file_field :video %>
  </div>

  <br>

  <%= f.label :youtube_url %>
  <%= f.text_field :youtube_url, :size => 140 %>


  <%= f.submit "編集する" %>
  <% end %>

app/views/tweets/index.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">

<div class="index">
  <section id="title">
    <h2>安全な空の旅を― </h2>
  </section>

  <section id="prologue">
    <h21>―prologue―</h21>
    <h22>
      <p>飛行機の事故率は<span style="color:red;">0.001％</span>。</p>
      <p>この安全性を生み出しているのは、</p>
      <p>過去の事故の教訓と反省。</p>
      <p>事故を風化させず、</p>
      <p>空の安全をこれからも守っていくために。</p>
    </h22>
  </section>

  <h3> 記事一覧</h3>
  <div class="bg_pettern Polka">
      <p> <%= link_to "新規投稿はこちら", new_tweet_path, class:"new-posts" %> </p>
    <div class="tweets-container">
      <% @tweets.each do |t| %>
        <div class="tweet">
          <ul style = "list-style-type:none;">
          <p> <%= link_to t.user.name, user_path(t.user.id),class:"user-name" %> </p>
          <li> <%= link_to t.title, tweet_path(t.id), class:"title"%> </li>
          <div class="data">
            <p> <%= t.date %>@<%= t.place %> </p>
          </div>
          <div class="about">
            <div class="abouts">
              <li>
                <span class="col-1">機種</span>
                <span class="col-2"><%= t.model %></span>
              </li>
              <li>
                <span class="col-1">会社</span>
                <span class="col-2"><%= t.company %></span>
              </li>
              <li>
                <span class="col-1">死傷者</span>
                <span class="col-2"><%= t.people %>人</span>
              </li>
            </div>
            <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete, class:"star" do %>
                  <i class="fa-sharp fa-solid fa-star"></i> <%= t.likes.count %>
                <% end %>
              <% else %>
                <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post, class:"starstar" do %>
                  <i class="fa-sharp fa-solid fa-star"></i><%= t.likes.count%>
                <% end %>
              <% end %>      
            <% else %>
              <i class="fa-sharp fa-solid fa-star"></i><%= t.likes.count %>
            <% end %>

            <% if user_signed_in? && current_user.id == t.user_id %>
              <li> <%= link_to "編集する", edit_tweet_path(t.id),class:"edit" %>
              <%= link_to "削除する", tweet_path(t.id), method: :delete, class:"edit" %> </li>
            <% end %>
            <li><%= t.created_at.strftime('%Y/%m/%d') %></li>
          </div>
        </div>
      <% end %>

    </div>
  </div>

  <h4> タグ一覧 </h4>
    <div class="Polka2">
      <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
      <div class="tagtag">
        <% Tag.all.each do |t| %>
          <div class="tags">
            <%= check_box :tag_ids, t.name %><%= t.name %>
          </div>
        <% end %>
      <br> <%= submit_tag '検索', class:"tag_click" %> </br>
      </div>
      <% end %>



      <div class="tag">  
        <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
        <%= text_area_tag :tag, "", :size => "100" ,class:"tag_content"%>
        <%= submit_tag 'タグを追加', class:"tag_add" %>
        <% end %>
      </div>
    </div>
</div>

app/views/tweets/new.html.erb

<h1>飛行機事故</h1>
<h3>新規投稿ページ</h3>
<%= form_for @tweet do |f| %>

  <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_field :title, :size => 30 %>
  </div>


    <div class="field">
    <%= f.label :場所 %>
    <%= f.text_field :place, :size => 30 %>
    </div>


    <div class="field">
    <%= f.label :機種 %>
    <%= f.text_field :model, :size => 30 %>
    </div>


    <div class="field">
    <%= f.label :航空会社 %>
    <%= f.text_field :company, :size => 30 %>
    </div>


    <div class="field">
    <%= f.label :事故年月日 %>
    <%= f.date_field :date, :size => 30 %>
    </div>


  <div class="field">
    <%= f.label :乗客・乗員  %>
    <%= f.number_field :people, :size => 10 %>
  </div>


  <div class="field">
    <%= f.label :説明  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <div class="field">
  <%= f.label :image %>
  <%= f.file_field :image %>
  </div>

  <div class="field">
  <%= f.label :image2 %>
  <%= f.file_field :image2 %>
  </div>

  <div class="field">
  <%= f.label :video %>
  <%= f.file_field :video %>
  </div>

  <br>
  <div class="field">
  <%= f.label :youtube_url %>
  <%= f.text_field :youtube_url, :size => 140 %>
  </div>

  <div class='form-group'>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
          <% end %>
      </div>
  <% end %>
  </div>

  <%= f.submit "投稿する" %>

<% end %>

<%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb

<h3>記事詳細</h3>
<div class="myposts">
<div class="bg_pettern Polka">
  <div class="mytweet">
    <ul style = "list-style-type:none;">
    <div class="mytitle">
      <p> <%= @tweet.title %> </p>
    </div>
    <div class="mydata">
      <p> <%= @tweet.date %>発生@<%= @tweet.place %> </p>
    </div>
    <div class="mycreated">
    <li><%= @tweet.created_at.strftime('%Y/%m/%d')%>投稿</li>
    </div>
    <div class="myabout">
      <div class="myabouts">
        <li>
          <span class="col-1">機種</span>
          <span class="col-2"><%= @tweet.model %></span>
        </li>
        <li>
          <span class="col-1">会社</span>
          <span class="col-2"><%= @tweet.company %></span>
        </li>
        <li>
          <span class="col-1">死傷者</span>
          <span class="col-2"><%= @tweet.people %>人</span>
        </li>
      </div>
      <div class="mydetail">
        <h31>概要</h31>
        <li> <%= @tweet.about %> </li>
      </div>
      <div class="myimages">
        <h32>関連画像・動画</h32>
        <p><%= image_tag @tweet.image_url, size: "250x160" if @tweet.image? %></p>
        <p><%= image_tag @tweet.image2_url, size: "250x160" if @tweet.image2? %></p>
        <%=  video_tag @tweet.video_url ,:controls => true if @tweet.video?%>
        <% unless @tweet.youtube_url.blank? %>
          <p><iframe width="372" height="210" src="https://www.youtube.com/embed/<%= find_youtube_url(@tweet.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>
        <% end %>
      </div>
      <div class="myedit">
        <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <li> <%= link_to "編集する", edit_tweet_path(@tweet.id), class:"edit" %> </li>
        <li> <%= link_to "削除する", tweet_path(@tweet.id), method: :delete, class:"edit" %> </li>
        <% end %>
      </div>
    </div>
  </div>

  <div class="tagtag2">
    <% @tweet.tags.each do |tag| %>
      <div class="tags">
        <span><%= tag.name %></span>
      </div>
    <% end %>
  </div>

  <div class="gooduser">
    <h32>いいねしたユーザー</h32>
    <div class="goodusername">
      <% @tweet.liked_users.each do |user| %>
        <li>[ユーザー名]<%= user.name %>, [e-mail]<%= user.email%></li>
      <% end %>
    </div>
  </div>

  <div class="comment-wrapper">
    <h32>コメント一覧</h32>
    <div class="usercomments">
      <% @comments.each do |c| %>
        <div>
          <%= c.user.email unless c.user.blank? %>
          <br>
          <%= c.content %>
        </div>
          <br>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
        <%= f.text_area :content %>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
    <% end %>
  </div>


  <%= link_to "トップページに戻る", tweets_path, class:"edit" %>
</div>
</div>

app/views/users/..html.erb
<h1>Users#.</h1>
<p>Find me in app/views/users/..html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb

<div class="mypage">
  <div class="mypage Polka3">
    <h1>マイページ</h1>
    <div class="infor">
      <span class="box-title">ユーザー情報</span>
        <p>
          <span class="col-11">名前</span>
          <span class="col-21"><%= @user.name %></span>
        </p>
        <p>
          <span class="col-11">メールアドレス</span>
          <span class="col-21"><%= @user.email %></span>
        </p>
        <p>
          <span class="col-11">プロフィール</span>
          <span class="col-21"><%= @user.profile %></span>
        </p>
        <% if current_user.id == @user.id %>
          <%= link_to "編集する", edit_user_registration_path, class:"edit"%>
        <% end %>
    </div>

  <h3>ユーザーの投稿一覧</h3>
  <div class="bg_pettern Polka">
      <p> <%= link_to "新規投稿はこちら", new_tweet_path, class:"new-posts" %> </p>
    <div class="tweets-container">
      <% @user.tweets.each do |t| %>
        <div class="tweet">
          <ul style = "list-style-type:none;">
          <p> <%= link_to t.user.name, user_path(t.user.id),class:"user-name" %> </p>
          <li> <%= link_to t.title, tweet_path(t.id), class:"title"%> </li>
          <div class="data">
            <p> <%= t.date %>@<%= t.place %> </p>
          </div>
          <div class="about">
            <div class="abouts">
              <li>
                <span class="col-1">機種</span>
                <span class="col-2"><%= t.model %></span>
              </li>
              <li>
                <span class="col-1">会社</span>
                <span class="col-2"><%= t.company %></span>
              </li>
              <li>
                <span class="col-1">死傷者</span>
                <span class="col-2"><%= t.people %>人</span>
              </li>
            </div>
            <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete, class:"star" do %>
                  <i class="fa-sharp fa-solid fa-star"></i> <%= t.likes.count %>
                <% end %>
              <% else %>
                <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post, class:"starstar" do %>
                  <i class="fa-sharp fa-solid fa-star"></i><%= t.likes.count%>
                <% end %>
              <% end %>      
            <% else %>
              <i class="fa-sharp fa-solid fa-star"></i><%= t.likes.count %>
            <% end %>

            <% if user_signed_in? && current_user.id == t.user_id %>
              <li> <%= link_to "編集する", edit_tweet_path(t.id),class:"edit" %>
              <%= link_to "削除する", tweet_path(t.id), method: :delete, class:"edit" %> </li>
            <% end %>
            <li><%= t.created_at.strftime('%Y/%m/%d') %></li>
          </div>
        </div>
      <% end %>

    </div>
  </div>

  <h3>ユーザーがいいねした投稿一覧</h3>
  <div class="bg_pettern Polka">
    <div class="tweets-container">
      <% @user.liked_tweets.each do |t| %>
        <div class="tweet">
          <ul style = "list-style-type:none;">
          <p> <%= link_to t.user.name, user_path(t.user.id),class:"user-name" %> </p>
          <li> <%= link_to t.title, tweet_path(t.id), class:"title"%> </li>
          <div class="data">
            <p> <%= t.date %>@<%= t.place %> </p>
          </div>
          <div class="about">
            <div class="abouts">
              <li>
                <span class="col-1">機種</span>
                <span class="col-2"><%= t.model %></span>
              </li>
              <li>
                <span class="col-1">会社</span>
                <span class="col-2"><%= t.company %></span>
              </li>
              <li>
                <span class="col-1">死傷者</span>
                <span class="col-2"><%= t.people %>人</span>
              </li>
            </div>
            <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete, class:"star" do %>
                  <i class="fa-sharp fa-solid fa-star"></i> <%= t.likes.count %>
                <% end %>
              <% else %>
                <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post, class:"starstar" do %>
                  <i class="fa-sharp fa-solid fa-star"></i><%= t.likes.count%>
                <% end %>
              <% end %>      
            <% else %>
              <i class="fa-sharp fa-solid fa-star"></i><%= t.likes.count %>
            <% end %>

            <% if user_signed_in? && current_user.id == t.user_id %>
              <li> <%= link_to "編集する", edit_tweet_path(t.id),class:"edit" %>
              <%= link_to "削除する", tweet_path(t.id), method: :delete, class:"edit" %> </li>
            <% end %>
            <li><%= t.created_at.strftime('%Y/%m/%d') %></li>
          </div>
        </div>
      <% end %>
    </div>
  </div>

 <%= link_to "トップページに戻る", tweets_path, class:"edit" %>

</div>